server.port=8083
spring.application.name=customer-service

# Conexi�n a la misma base de datos MySQL de ventas
spring.datasource.url=jdbc:mysql://localhost:3306/db_cordillera_sales?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Configuraci�n de JPA para Hibernate
spring.jpa.show-sql=true
# Nota: Usamos 'update' para que Hibernate cree la tabla 'customers' autom�ticamente
# sin chocar con el Flyway de las ventas.
spring.jpa.hibernate.ddl-auto=update

# Desactivamos Flyway en este microservicio espec�fico para evitar conflictos de historial
spring.flyway.enabled=false

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always