server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: group-cordillera
          uri: lb://GROUP-CORDILLERA
          predicates:
            - Path=/api/v1/sales/**

        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**

        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**

        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/v1/employees/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**

        - id: supplier-service
          uri: lb://SUPPLIER-SERVICE
          predicates:
            - Path=/api/v1/suppliers/**

        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/api/v1/deliveries/**

        - id: discount-service
          uri: lb://DISCOUNT-SERVICE
          predicates:
            - Path=/api/v1/discounts/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Clientes
        url: /api/v1/customers/v3/api-docs
      - name: Inventario
        url: /api/v1/inventory/v3/api-docs
      - name: Ventas
        url: /api/v1/sales/v3/api-docs