server.port=8083
spring.application.name=customer-service

# Conexión a la misma base de datos MySQL de ventas
spring.datasource.url=jdbc:mysql://localhost:3306/db_cordillera_sales?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=


spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update


spring.flyway.enabled=false

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always