server.port=8084
spring.application.name=employee-service

# Conexi�n a la misma base de datos MySQL de tus otros servicios
spring.datasource.url=jdbc:mysql://localhost:3306/db_cordillera_sales?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Configuraci�n de JPA para Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Desactivamos Flyway para este servicio espec�fico
spring.flyway.enabled=false

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always